"""
schemas/feedback_schema.py
--------------------------
Pydantic schemas define the shape of data going IN and OUT of the API.

Why separate from the ORM model?
  - The ORM model talks to the database.
  - Pydantic schemas validate and serialize HTTP request/response data.
  - This separation is called the "DTO pattern" (Data Transfer Object).

We define 3 schemas:
  1. FeedbackBase    → shared fields between Create and Response
  2. FeedbackCreate  → fields required when creating a new feedback (POST)
  3. FeedbackUpdate  → fields allowed when updating feedback (PUT) — all optional
  4. FeedbackResponse→ what the API returns to the client
"""

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field, field_validator


# -------------------------------------------------------------------
# 1. Base Schema — shared fields used in both input and output
# -------------------------------------------------------------------
class FeedbackBase(BaseModel):
    """
    Common fields shared by Create and Response schemas.
    Using Field() lets us add metadata like description, min/max for Swagger docs.
    """

    participant_name: str = Field(
        ...,                           # '...' means the field is required
        min_length=2,
        max_length=150,
        description="Full name of the participant submitting feedback",
        examples=["Alice Johnson"],
    )

    program_name: str = Field(
        ...,
        min_length=2,
        max_length=200,
        description="Name of the program or course being reviewed",
        examples=["Data Science Bootcamp"],
    )

    rating: int = Field(
        ...,
        ge=1,                          # greater than or equal to 1
        le=5,                          # less than or equal to 5
        description="Rating from 1 (poor) to 5 (excellent)",
        examples=[4],
    )

    comments: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Optional detailed feedback or comments",
        examples=["Great program with excellent instructors!"],
    )

    # -------------------------------------------------------------------
    # Custom Validator: strip extra whitespace from string fields
    # -------------------------------------------------------------------
    @field_validator("participant_name", "program_name", mode="before")
    @classmethod
    def strip_whitespace(cls, value: str) -> str:
        """Removes leading/trailing spaces from name fields."""
        if isinstance(value, str):
            return value.strip()
        return value


# -------------------------------------------------------------------
# 2. Create Schema — used for POST /feedback requests
#    Inherits all fields from FeedbackBase (no extra fields needed here)
# -------------------------------------------------------------------
class FeedbackCreate(FeedbackBase):
    """
    Schema for creating a new feedback entry.
    The client sends: participant_name, program_name, rating, comments.
    We do NOT accept feedback_id or submitted_at (auto-generated by DB).
    """
    pass


# -------------------------------------------------------------------
# 3. Update Schema — used for PUT /feedback/{id} requests
#    All fields are Optional so clients can update just one field at a time
# -------------------------------------------------------------------
class FeedbackUpdate(BaseModel):
    """
    Schema for updating an existing feedback entry.
    All fields are optional — the client only sends what they want to change.
    """

    participant_name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=150,
        description="Updated participant name",
    )

    program_name: Optional[str] = Field(
        default=None,
        min_length=2,
        max_length=200,
        description="Updated program name",
    )

    rating: Optional[int] = Field(
        default=None,
        ge=1,
        le=5,
        description="Updated rating (1–5)",
    )

    comments: Optional[str] = Field(
        default=None,
        max_length=1000,
        description="Updated comments",
    )

    @field_validator("participant_name", "program_name", mode="before")
    @classmethod
    def strip_whitespace(cls, value):
        if isinstance(value, str):
            return value.strip()
        return value


# -------------------------------------------------------------------
# 4. Response Schema — what the API returns to the client
#    Includes all base fields PLUS the auto-generated fields from the DB
# -------------------------------------------------------------------
class FeedbackResponse(FeedbackBase):
    """
    Schema for returning feedback data in API responses.
    Adds the DB-generated fields: feedback_id and submitted_at.
    """

    feedback_id: int = Field(description="Unique identifier for the feedback entry")
    submitted_at: datetime = Field(description="Timestamp when the feedback was submitted")

    class Config:
        """
        from_attributes=True tells Pydantic to read data from ORM model
        attributes (not just plain dicts). Required for SQLAlchemy integration.
        """
        from_attributes = True


# -------------------------------------------------------------------
# 5. Generic API Response wrapper — for consistent response structure
# -------------------------------------------------------------------
class APIResponse(BaseModel):
    """
    A standard wrapper for all API responses.
    Provides consistent structure: { success, message, data }
    """
    success: bool = Field(description="Whether the operation was successful")
    message: str = Field(description="Human-readable status message")
    data: Optional[FeedbackResponse] = Field(
        default=None,
        description="The feedback record (if applicable)",
    )
